### ISSUE TITLE
Update MQ example to use the client from Maven

### ISSUE THREAD

**Issue by TimMoore** [lagom/ibm-integration-examples#16]
It looks like the MQ client is now available from Maven Central: 

https://developer.ibm.com/messaging/2018/01/09/developing-mq-java-applications-maven/
https://mvnrepository.com/artifact/com.ibm.mq/com.ibm.mq.allclient/9.0.4.0

This could be used to simplify the instructions for running.

**Comment by ignasi35** [comment]
Warning: The instructions state version `9.0.0.1` is necessary while the version on maven central is `9.0.4.0`.

**Comment by TimMoore** [comment]
Yes, but it's probably a good idea to stay up to date anyway. The instructions, as provided, actually run version 9.0.4.0 of the server. It seemed to be fine.

I guess if version 9.0.4.0 of the client gives us any problems, we can drop this.
